apiVersion:  apps/v1
kind: Deployment
metadata:
  namespace: default
  name: uredis
  labels:
    app: uredis
spec:
  selector:
    matchLabels:
      app: uredis
  template:
    metadata:
      namespace: default
      name: uredis
      labels:
        app: uredis
    spec:
      containers:
        - name: uredis
          image: your_image/here
          envFrom:
            - configMapRef:
                name: cm-uredis
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: cm-uredis
  labels:
    app: uredis
data:
  REDIS_URL: YOUR_REDIS_URL